table FatoAvaliacaoFornecedor
	lineageTag: 1faf673c-a596-473b-ae92-ac986c5f3271

	measure 'Nota Geral Fornecedor' = ```
			
			AVERAGEX(FatoAvaliacaoFornecedor, 
			    (FatoAvaliacaoFornecedor[Nota_Qualidade] * 0.3) +
			    (FatoAvaliacaoFornecedor[Nota_Prazo] * 0.3) +
			    (FatoAvaliacaoFornecedor[Nota_Preco] * 0.2) +
			    (FatoAvaliacaoFornecedor[Nota_Risco] * 0.2)
			)
			```
		formatString: 0.0
		lineageTag: 0dcb9f0c-3e4d-47d9-b9f6-cdda9130dbd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Classificacao Fornecedor' =
			
			SWITCH(TRUE(),
			    [Nota Geral Fornecedor] >= 8, "Estratégico",
			    [Nota Geral Fornecedor] >= 6, "Aprovado",
			    [Nota Geral Fornecedor] >= 4, "Em Observação",
			    "Crítico"
			)
		lineageTag: 8d190f36-571e-4018-97ae-af49d508949e

	measure 'Total Nao Conformidades' = SUM(FatoAvaliacaoFornecedor[Ocorrencias_Nao_Conformidade])
		formatString: 0
		lineageTag: d1bd1c37-9e98-4e1b-9f68-314b29145291

	measure 'Media Nota Qualidade' = AVERAGE(FatoAvaliacaoFornecedor[Nota_Qualidade])
		formatString: 0.0
		lineageTag: 88ce9024-373f-4f2e-a0e2-4d83c077fd54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media Nota Prazo' = AVERAGE(FatoAvaliacaoFornecedor[Nota_Prazo])
		formatString: 0.0
		lineageTag: 29b468eb-1eb5-4d15-86d3-49f89bbfc81c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Fornecedores Avaliados' = DISTINCTCOUNT(FatoAvaliacaoFornecedor[ID_Fornecedor])
		formatString: 0
		lineageTag: cb06d90b-402e-4c64-8334-736b03e5e079

	measure '% Fornecedores Estrategicos' = ```
			
			VAR FornecedoresEstrategicos = 
			    CALCULATETABLE(
			        SUMMARIZE(FatoAvaliacaoFornecedor,DimFornecedor[ID_Fornecedor]),
			        FILTER(FatoAvaliacaoFornecedor, [Nota Geral Fornecedor] >= 8)
			    )
			RETURN DIVIDE(COUNTROWS(FornecedoresEstrategicos), [Qtd Fornecedores Avaliados], 0)
			```
		formatString: 0.0%
		lineageTag: ea84e14f-e8d3-450d-a3b4-4e89ce685107

	column ID_Avaliacao
		dataType: string
		lineageTag: 9579c28e-6b51-4a51-b757-38eff4c3f64f
		summarizeBy: none
		sourceColumn: ID_Avaliacao

		annotation SummarizationSetBy = Automatic

	column ID_Fornecedor
		dataType: string
		lineageTag: ed762a71-27f9-4fec-bc24-be2434045946
		summarizeBy: none
		sourceColumn: ID_Fornecedor

		annotation SummarizationSetBy = Automatic

	column Data_Avaliacao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 086a9d62-3fdb-4e70-b2cb-e3a2fa43597f
		summarizeBy: none
		sourceColumn: Data_Avaliacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Trimestre_Label
		dataType: string
		lineageTag: 151df8f9-873c-4ef2-85de-fdfe02bb461e
		summarizeBy: none
		sourceColumn: Trimestre_Label

		annotation SummarizationSetBy = Automatic

	column Nota_Qualidade
		dataType: double
		lineageTag: e98b8643-6463-47c6-b111-79f0af437551
		summarizeBy: sum
		sourceColumn: Nota_Qualidade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nota_Prazo
		dataType: double
		lineageTag: c25020a8-f749-4f39-a340-5a4dfed9bd25
		summarizeBy: sum
		sourceColumn: Nota_Prazo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nota_Preco
		dataType: double
		lineageTag: 23f986df-16e7-43df-a4d4-e50ca0023cec
		summarizeBy: sum
		sourceColumn: Nota_Preco

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nota_Risco
		dataType: double
		lineageTag: 2a331d69-0a0f-4279-8942-e326895b9fb9
		summarizeBy: sum
		sourceColumn: Nota_Risco

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ocorrencias_Nao_Conformidade
		dataType: int64
		formatString: 0
		lineageTag: 690804f1-3ab6-4658-ab5a-346985f89cd1
		summarizeBy: sum
		sourceColumn: Ocorrencias_Nao_Conformidade

		annotation SummarizationSetBy = Automatic

	partition FatoAvaliacaoFornecedor = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\costa\Downloads\base_supplier_scorecard.xlsx"), null, true),
				    FatoAvaliacaoFornecedor_Sheet = Fonte{[Item="FatoAvaliacaoFornecedor",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(FatoAvaliacaoFornecedor_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Avaliacao", type text}, {"ID_Fornecedor", type text}, {"Data_Avaliacao", type date}, {"Trimestre_Label", type text}, {"Nota_Qualidade", type number}, {"Nota_Prazo", type number}, {"Nota_Preco", type number}, {"Nota_Risco", type number}, {"Ocorrencias_Nao_Conformidade", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

